### ISSUE TITLE
Where download LRpair_human.rds？

### ISSUE THREAD

**Issue by yliuup** [liuqivandy/SpaGene#3]

**Comment by liuqivandy** [comment]
You can use any LR pair database.
We downloaded the LR pair from CellTalkDB.
 https://academic.oup.com/bib/article-abstract/22/4/bbaa269/5955941?redirectedFrom=fulltext

From: Ocean ***@***.***>
Date: Saturday, October 1, 2022 at 11:32 PM
To: liuqivandy/SpaGene ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liuqivandy/SpaGene] Where download LRpair_human.rds？ (Issue #3)

**Comment by yliuup** [comment]
Thank you very much!
